### ISSUE TITLE
[PL][SPELL][SHAMAN] Windfury Weapon

### ISSUE THREAD

**Issue by Artur97** [JarGames/Darkmoon-Bugtracker#11]
Normalnie windfury weapon zadaje nature dmg. Na jg niestety nie zadaje nature dmg, co niestety psuje główne zródło obrażeń enha. Mozna to sprawdzic używając Stormstrike, ktory zwiększa nature dmg i ma na to 4 stacki. Po użyciu spella nature dmg stacki schodzą, a po odpaleniu sie wf juz nie. Prosze to naprawić, bo mi to psuje dmg na enha ://

**Comment by JarGames** [comment]
Windfury weapon nie zadawał w WotLKu nature damagu - pisałem o tym z tobą na priv (wysłałem link do battle.netu z tamtego okresu).
